### ISSUE TITLE
Add support for environment variables

### ISSUE THREAD

**Issue by roland-d** [xinningsu/craft-sftp#1]
Hello,

Thank you for this plugin. While testing how the plugin works I noticed that the use of environment variables is not supported. For example if I enter `$SFTP_HOSTNAME` the plugin tries to connect to `$SFTP_HOSTNAME` instead of the actual hostname.

I believe the change needed is `craft\helpers\App::parseEnv($this->host)` for the hostname for example.

This would be a great addition.

Thank you.

**Comment by xinningsu** [comment]
It's fixed in new release. sorry for late.
